name: auto-minor-release

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    if: >-
      ${{ (github.event_name == 'push' && github.ref == 'refs/heads/main') ||
          (github.event_name == 'pull_request' && github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Configure git user
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Install deps
        run: npm ci --no-audit --no-fund --ignore-scripts

      - name: Bump minor version and push tag
        run: |
          NEW_VER=$(npm version minor -m "chore(release): %s")
          echo "NEW_VER=$NEW_VER" >> $GITHUB_ENV
          git push --follow-tags

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.NEW_VER }}
          name: Release ${{ env.NEW_VER }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
